AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  pdftotext:
    Type: AWS::Serverless::Function
    Properties:
      Description: Extract text from PDF
      Handler: index.handler
      Runtime: nodejs6.10
      Code:
        Files:
          - index.js
          - pdftotext
